unqualified-search-registries = ["docker.io"]

[[registry]]
location = "docker.io"

[[registry]]
location = "ghcr.io"

[[registry]]
prefix = "azurecr.io"
location = "azurecr.io"

[[registry]]
prefix = "public.ecr.aws"
location = "public.ecr.aws"

[[registry]]
prefix = "*.dkr.ecr.*.amazonaws.com"
location = "*.dkr.ecr.*.amazonaws.com"
